import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import RootProviders from "@/components/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProviders>
          <Navbar />
          
          {children}
        
          <Footer />
        </RootProviders>
      </body>
    </html>
  );
}
